from collections import namedtuple

Servant = namedtuple('Servant', ['name', 'ascension', 'skills', 'need'])

servants = [
    Servant('Miyamoto Musashi', 5, [10,10,10], 'Need'),
    Servant('Arthur Pendragon (Prototype)', 5, [6,6,6], 'Need'),
    Servant('Nero Claudius (Bride)', 5, [10,10,6], 'Need'),
    Servant('Okita Souji', 5, [6,6,6], 'Need'),
    Servant('Nikola Tesla', 5, [6,10,10], 'Need'),
    Servant('Altria Pendragon (Rider Alter)', 5, [8,6,6], 'Need'),
    Servant('Merlin', 5, [10,10,10], 'Need'),
    Servant('Xuanzang Sanzang', 5, [10,6,10], 'Need'),
    Servant('First Hassan', 5, [6,10,10], 'Need'),
    Servant('Sessyoin Kiara', 5, [6,6,2], 'Need'),
    Servant('Katsushika Hokusai', 5, [10,6,6], 'Need'),
    Servant('Abigail Williams', 5, [8,6,6], 'Need'),
    Servant('Attila the San(ta)', 5, [6,6,6], 'Need'),
    Servant('Archer of Inferno', 5, [6,6,6], 'Need'),
    Servant('Oda Nobunaga', 5, [6,6,6], 'Want'),
    Servant('EMIYA', 5, [6,6,6], 'Want'),
    Servant("Jeanne d'Arc (Alter Santa Lily)", 5, [6,6,6], 'Want'),
    Servant('Altria Pendragon (Lancer Alter)', 5, [6,6,6], 'Want'),
    Servant('Elisabeth Bathory', 5, [6,6,6], 'Want'),
    Servant('Ishtar (Rider)', 5, [6,6,6], 'Need'),
    Servant('Sakata Kintoki (Rider)', 5, [9,7,6], 'Want'),
    Servant('Saint Martha', 5, [6,6,6], 'Want'),
    Servant('Gilgamesh (Caster)', 5, [6,6,6], 'Need'),
    Servant('Nitocris', 5, [6,8,6], 'Need'),
    Servant('Assassin of Paraiso', 5, [6,6,6], 'Want'),
    Servant('Scathach (Assassin)', 5, [6,6,6], 'Need'),
    Servant('Chacha', 5, [1,1,1], 'Want'),
    Servant('Heracles', 5, [8,7,6], 'Need'),
    Servant('Saint Martha (Ruler)', 5, [2,6,6], 'Need'),
    Servant('Gorgon', 5, [9,6,6], 'Need'),
    Servant('Mecha Eli-chan', 5, [6,6,6], 'Need'),
    Servant('BB', 5, [10,6,6], 'Need'),
    Servant('Mash Kyrielight', 5, [9,8,6], 'Need'),
    Servant('Caster of Midrash', 5, [4,4,6], 'Need'),
    Servant('Frankenstein', 5, [5,4,6], 'Need'),
    Servant('Karna', 4, [4,7,10], 'Need'),
    Servant('Passionlip', 5, [1,1,1], 'Need'),
    Servant('Bedivere', 5, [6,1,6], 'Want'),
    Servant('Fergus mac Roich', 5, [4,4,2], 'Want'),
    Servant('Gaius Julius Caesar', 5, [2,6,1], 'Want'),
    Servant('David', 5, [4,2,1], 'Need'),
    Servant('Euryale', 5, [4,1,6], 'Need'),
    Servant('Robin Hood', 5, [1,1,1], 'Want'),
    Servant('Jaguar Warrior', 5, [1,1,1], 'Want'),
    Servant('Cu Chulainn', 5, [1,1,2], 'Want'),
    Servant('Ushiwakamaru', 5, [4,8,1], 'Want'),
    Servant('Medusa', 5, [2,1,1], 'Want'),
    Servant('Nursery Rhyme', 5, [1,1,1], 'Want'),
    Servant('Medea', 5, [1,1,1], 'Want'),
    Servant('Fuuma Kotarou', 5, [1,1,1], 'Want'),
    Servant('Lu Bu Fengxian', 5, [1,1,1], 'Want'),
    Servant('Georgios', 5, [1,1,1], 'Need'),
    Servant('Hans Christian Andersen', 5, [1,6,1], 'Want'),
    Servant('Hassan of the Cursed Arm', 5, [2,2,2], 'Want'),
    Servant('Arash', 5, [1,1,5], 'Want'),
    Servant('Ryougi Shiki (Assassin)', 4, [6,4,6], 'Need'),
    Servant('Hassan of the Serenity', 5, [1,1,1], 'Want'),
    Servant('Paul Bunyan', 5, [1,1,1], 'Need'),
    Servant('Spartacus', 5, [1,4,1], 'Need'),
    Servant('Leonidas', 5, [1,1,1], 'Want'),
    Servant('Asagami Fujino', 2, [6,1,1], 'Need'),
    Servant('Boudica', 3, [1,1,1], 'Want'),
    Servant("Chevalier d'Eon", 2, [1,1,1], 'Need'),
    Servant('Asterios', 3, [1,1,1], 'Want'),
    Servant('Diarmuid ua Duibhne', 2, [1,1,1], 'Want'),
    Servant('Kid Gilgamesh', 2, [6,1,1], 'Want'),
    Servant('William Shakespeare', 3, [1,1,1], 'Want'),
    Servant('Elisabeth Bathory (Brave)', 1, [1,1,1], 'Want'),
    Servant('Cu Chulainn (Prototype)', 2, [1,1,1], 'Want'),
    Servant('Jing Ke', 2, [2,1,1], 'Want'),
    Servant('EMIYA (Assassin)', 1, [1,1,1], 'Want'),
    Servant('Charles-Henri Sanson', 2, [1,2,1], 'Want'),
    Servant('Kiyohime', 1, [1,1,1], 'Want'),
    Servant('Fionn mac Cumhaill', 1, [1,1,1], 'Want'),
    Servant('Gilles de Rais', 1, [1,1,1], 'Want'),
    Servant('Mata Hari', 2, [1,1,1], 'Want'),
    Servant('Sasaki Kojirou', 2, [2,1,1], 'Want'),
    Servant('Musashibou Benkei', 1, [1,1,1], 'Want'),
    Servant('Phantom of the Opera', 1, [1,1,1], 'Want'),
    Servant('Ibaraki-Douji', 1, [1,1,1], 'Want'),
    Servant('Altria Pendragon (Lily)', 1, [1,1,1], 'Want'),
    Servant('Tawara Touta', 1, [1,1,1], 'Want'),
    Servant('Billy the Kid', 1, [1,1,1], 'Want'),
    Servant('Houzouin Inshun', 1, [1,1,1], 'Want'),
    Servant('Hektor', 1, [1,1,1], 'Want'),
    Servant('Romulus', 1, [1,1,1], 'Want'),
    Servant('Alexander', 1, [1,1,1], 'Want'),
    Servant('Edward Teach', 1, [1,1,1], 'Want'),
    Servant('Sieg', 1, [1,1,1], 'Want'),
    Servant('Avicebron', 1, [1,1,1], 'Want'),
    Servant('Geronimo', 1, [1,1,1], 'Want'),
    Servant('Charles Babbage', 1, [1,1,1], 'Want'),
    Servant('Paracelsus von Hohenheim', 1, [1,1,1], 'Want'),
    Servant('Cu Chulainn (Caster)', 1, [1,1,1], 'Want'),
    Servant('Mephistopheles', 1, [1,1,1], 'Want'),
    Servant('Gilles de Rais (Caster)', 1, [1,1,1], 'Want'),
    Servant('Wolfgang Amadeus Mozart', 1, [1,1,1], 'Want'),
    Servant('Hassan of the Hundred Personas', 1, [1,1,1], 'Want'),
    Servant('Henry Jekyll & Hyde', 1, [1,1,1], 'Want'),
    Servant('Darius III', 1, [1,1,1], 'Want'),
    Servant('Eric Bloodaxe', 1, [1,1,1], 'Want'),
    Servant('Caligula', 1, [1,1,1], 'Want'),
    Servant('Antonio Salieri', 1, [1,1,1], 'Want')
]